DefaultMesh and STL update
imagej/imagej-mesh pull request #3
Opened 2016-12-08 10:19 UTC by kephale

Moving imagej-ops DefaultMesh to this library and updating the STL
meshes to use it

2016-12-08 10:20 UTC, kephale commented
I leave this PR open for debate. This contains @tibuch 's DefaultMesh from ops, because we haven't discussed where this library fits in the dependency hierarchy. However, meshes made with this library *need* to be the same meshes that we're using in ops.

2016-12-08 10:22 UTC, kephale commented
Pinging @rimadoma on this too

2016-12-28 13:00 UTC, ctrueden requested changes
Most important thing is to fix the POM parent. Other than that, would be nice to split the commits.

2016-12-28 13:00 UTC, ctrueden commented on pom.xml
> +		<version>16.5.0</version>
Please fix this... it needs to be `org.scijava:pom-scijava:12.0.0`, _not_ the obsolete `pom-imagej` anymore.

2016-12-28 13:00 UTC, ctrueden commented on src/main/java/net/imagej/plugins/io/mesh/stl/BinarySTLFormat.java
> +		writeVector(buffer, facet.getNormal());
This is great, but better to do as two separate commits. The first one adds @tibuch's mesh classes, and the second one changes the code here accordingly?

2016-12-28 13:00 UTC, ctrueden commented on src/main/java/net/imagej/plugins/io/mesh/stl/BinarySTLFormat.java
> +import org.apache.commons.math3.geometry.euclidean.threed.Vector3D;
Actually, is this change directly related to the change over to `Mesh`? Maybe this should be yet another separate commit? From JavaFX's `Vec3f` to Commons Math 3's `Vector3D`?

2016-12-28 17:17 UTC, kephale commented
I opened a new pull request with the commits split: https://github.com/imagej/imagej-mesh/pull/5

2016-12-30 13:14 UTC, ctrueden commented
@kephale wrote:
> I opened a new pull request with the commits split: #5

No need to do that. Just force push over the old branch, and the PR will magically update.

2016-12-30 13:14 UTC, ctrueden commented
Closing in favor of #5.

2016-12-30 13:14 UTC, closed without merging